import React from "react";

export const metadata = {
  title: "Welcome!",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  return <div>Hi this is sample</div>;
}
